/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import game.GameManager;
import model.Globo;

import javax.swing.*;
import java.awt.*;

public class VentanaJuego extends JFrame {

    private Image fondo;
    private BarraInfo barraInfo;
    private JPanel zonaJuego;

    public VentanaJuego() {

        GameManager manager = GameManager.getInstance();

        setTitle("🎈 Captura los Globos");
        setSize(900, 700);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());

        // ✅ Ruta correcta
        fondo = new ImageIcon(
                getClass().getResource("/recursos/fondo.jpg")
        ).getImage();

        // Barra superior
        barraInfo = new BarraInfo();
        add(barraInfo, BorderLayout.NORTH);

        // Zona de juego
        zonaJuego = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                // Fondo
                g.drawImage(fondo, 0, 0, getWidth(), getHeight(), this);

                // Globos
                for (Globo globo : manager.getEstado().getGlobos()) {
                    globo.dibujar(g);
                }
            }
        };

        zonaJuego.setOpaque(false);
        add(zonaJuego, BorderLayout.CENTER);

        // 🔥 MUY IMPORTANTE: decirle al GameManager el tamaño real
        manager.setZonaJuego(zonaJuego);

        // Click para reventar globos
        zonaJuego.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                manager.procesarClick(e.getX(), e.getY());
            }
        });

        // Timer de repintado y actualización
        new Timer(30, e -> {
            barraInfo.actualizar();
            zonaJuego.repaint();
        }).start();

        setVisible(true);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
    ex.printStackTrace();
}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaJuego().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
